# © Copyright 2025 Stuart Parmenter
# SPDX-License-Identifier: MIT

substitutions:
  PANEL_W: "64"
  PANEL_H: "64"

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    advanced:
      compiler_optimization: PERF
      execute_from_psram: true
      enable_idf_experimental_features: true
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y

psram:
 mode: octal
 speed: 80MHz

# ---- I²S bus for mic ----
i2s_audio:
  id: i2s_mic_bus
  i2s_lrclk_pin: GPIO12
  i2s_bclk_pin:  GPIO11

# ---- Microphone Configuration ----
# Hardware: I²S digital microphone
#
# Data format:
# - 24-bit samples left-justified in 32-bit words
# - Raw values ≈ ±(0x00600000) with low 8 bits always 0x00 (padding)
# - Convert with (raw >> 8) / 2^23
microphone:
  - platform: i2s_audio
    id: m1_mic
    adc_type: external
    i2s_din_pin: GPIO10
    sample_rate: 16000
    bits_per_sample: 32bit
    use_apll: true
    pdm: false
    channel: left
    i2s_mode: primary
    i2s_audio_id: i2s_mic_bus

display:
  - platform: hub75
    id: matrix
    board: apollo-automation-m1-rev6

    panel_width: ${panel_width}
    panel_height: ${panel_height}
    layout: ${layout}
    layout_rows: ${layout_rows}
    layout_cols: ${layout_cols}
    scan_wiring: ${scan_wiring}

    clock_phase: false
    latch_blanking: 1
    clock_speed: 20MHz

    bit_depth: 8

    # for LVGL
    double_buffer: false
    auto_clear_enabled: false
    update_interval: never

switch:
  - platform: template
    id: mic_mute_sw
    name: "Microphone Enabled"
    icon: "mdi:microphone"
    restore_mode: ALWAYS_ON
    lambda: |-
      return !id(m1_mic).get_mute_state();
    turn_on_action:
      - microphone.unmute: m1_mic
    turn_off_action:
      - microphone.mute: m1_mic

lvgl:
  buffer_size: 100%
  displays:
    - matrix
